Social_Web/Social_Web/urls.py
from django.contrib import admin
from django.urls import path, include
from account import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('posts/', include('post.urls')),
    path('', views.home, name='home')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Social_Web/account/urls.py
from django.urls import path
from account import views

app_name = "account"

urlpatterns = [
    path('signup/', views.signup , name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('search-user/', views.search_user, name='search_user'),
    path('user/<username>/', views.other_profile, name='other_profile'),
    path('follow/<username>/', views.follow_user, name='follow_user'),
    path('unfollow/<username>/', views.unfollow_user, name='unfollow_user')
]

Social_Web/post/urls.py
from django.urls import path 
from post import views


app_name = 'post'

urlpatterns = [
    path('upload/', views.upload, name='upload' ),
    path('like/<pk>/', views.like , name = 'like'),
    path('unlike/<pk>/', views.unlike , name = 'unlike'),
    path('detail-post/<pk>', views.detail_post, name='detail_post'),
    path('delete-post/<pk>', views.delete_post, name='delete_post')
]

Social_Web/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{% block title %}  {% endblock %}</title>
    {% block css %}

    {% endblock %}
  </head>
  <body>
    {% block body %}

    {% endblock%}
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

Social_Web/templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    
    <title>{% block title %} {% endblock %}</title>
    {% block css %} {% endblock %}
  </head>
  <body>
    <div class="container-fluid ">
      <div class="row flex-nowrap ">
        <div class="d-none d-md-block  col-auto col-md-1 col-xl-2 sticky-top  border-right" style="height: 100vh;">
          <div class="">
            <ul class="nav nav-pills flex-column mt-2 text-dark">
              <li class="nav-item  mb-5">
                <a href="{% url 'home' %}" class="nav-link text-dark">
                  <i class="fa-solid fa-people-arrows d-inline d-xl-none" style="font-size: 25px; margin-right: 16px;"></i>
                  <span class="d-none d-xl-inline font-italic" style="font-size: 30px;">Social</span>
                </a>
              </li>
              <li class="nav-item mb-4">
                <a href="{% url 'home' %}" class="nav-link text-dark d-flex align-items-center" style="font-size: 15px;">
                  <i class="fa fa-home " style="font-size: 25px; margin-right: 16px;"></i>
                  <span class="d-none d-xl-inline  ">Home</span>
                </a>
              </li>
              <li class="nav-item mb-4">
                <a href="{% url 'home' %}" class="nav-link text-dark d-flex align-items-center" style="font-size: 15px;" data-toggle="modal" data-target="#exampleModal">
                  <i class="fa-solid fa-magnifying-glass" style="font-size: 28px; margin-right: 16px;"></i>
                  <span class="d-none d-xl-inline  ">Search</span>
                </a>
              </li>
              <li class="nav-item mb-4">
                <a href="{% url 'post:upload' %}" class="nav-link text-dark d-flex align-items-center" style="font-size: 15px; cursor: pointer;" >
                  <i class="fa-solid fa-plus" style="font-size: 30px; margin-right: 20px;"></i>
                  <span class="d-none d-xl-inline  ">Post</span>
                </a>
              </li>

              

              <li class="nav-item mb-4">
                <a href="{% url 'account:profile' %}" class="nav-link text-dark d-flex align-items-center" style="font-size: 15px;">
                  {% if user.profile.profile_pic %}
                    <img src="/media/{{user.profile.profile_pic}}" height="30" width="30" style="margin-right: 16px;" alt="" srcset="" class="rounded-circle">
                  {% else %}
                    <i class="fa-solid fa-user" style="font-size: 25px;margin-right: 20px;"></i>
                  {% endif %}

                  <span class="d-none d-xl-inline  ">Profile</span>
                </a>
              </li>

              
              <li class="nav-item mb-4">
                <a href="{% url 'account:logout' %}" class="nav-link text-dark d-flex align-items-center" style="font-size: 15px;">
                  <i class="fa fa-sign-out " style="font-size: 25px;margin-right: 16px;" aria-hidden="true"></i>
                  <span class="d-none d-xl-inline ">Logout</span>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-12 col-md-11 col-xl-10">{% block body %} {% endblock%}</div>

      </div>
    </div>
      <div class="fixed-bottom d-md-none bg-light">
        <ul class="nav nav-pills d-flex justify-content-around  text-dark">
          
          <li class="nav-item">
            <a href="{% url 'home' %}" class="nav-link text-dark d-flex align-items-center" style="font-size: 15px;">
              <i class="fa fa-home " style="font-size: 23px;"></i>
            </a>
          </li>

          <li class="nav-item">
            <a href="{% url 'home' %}" class="nav-link text-dark d-flex align-items-center" style="font-size: 15px;" data-toggle="modal" data-target="#exampleModal">
              <i class="fas fa-magnifying-glass " style="font-size: 23px; "></i>
            </a>
          </li>

          <li class="nav-item">
            <a href="{% url 'post:upload' %}"  class="nav-link text-dark d-flex align-items-center" style="font-size: 15px;" >
              <i class="fa-solid fa-plus" style="font-size: 23px;"></i>
            </a>
          </li>
         
          <li class="nav-item ">
            <a href="{% url 'account:profile' %}" class="nav-link text-dark d-flex align-items-center" style="font-size: 15px;">
              {% if user.profile.profile_pic %}
                <img src="/media/{{user.profile.profile_pic}}" height="28" width="28" style="margin-right: 16px;" alt="" srcset="" class="rounded-circle">
              {% else %}
                <i class="fa-solid fa-user" style="font-size: 23px;"></i>
              {% endif %}

            </a>
          </li>
          
          <li class="nav-item ">
            <a href="{% url 'account:logout' %}" class="nav-link text-dark d-flex align-items-center" style="font-size: 15px;">
              <i class="fa fa-sign-out " style="font-size: 23px;" aria-hidden="true"></i>
             
            </a>
          </li>
        </ul>
      </div>

      <div class="fixed-top d-md-none bg-light">
        <ul class=" nav d-flex flex-nowrap mt-2  justify-content-around">
          <li class="nav-item ">
            <a href="{% url 'home' %}" class="nav-link text-dark">Social
            </a>
          </li>
          <li class="nav-item  ">
            <form action="{% url 'account:search_user' %}"  method="GET">
              <input type="text" name="search" placeholder="Search" id=""><br>
            </form>
          </li>
        </ul>

      </div>

     


    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">
            <form action="{% url 'account:search_user' %}" method="GET">
              <input type="text" name="search" placeholder="Search" id="" class="form-control"><br>
            </form>
          </div>

        </div>
      </div>
    </div>





    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://kit.fontawesome.com/3031768ff7.js" crossorigin="anonymous"></script>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>