Social_Web/Social_Web/urls.py
from django.contrib import admin
from django.urls import path, include
from account import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('posts/', include('post.urls')),
    path('', views.home, name='home')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Social_Web/account/urls.py
from django.urls import path
from account import views

app_name = "account"

urlpatterns = [
    path('signup/', views.signup , name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('search-user/', views.search_user, name='search_user'),
    path('user/<username>/', views.other_profile, name='other_profile'),
    path('follow/<username>/', views.follow_user, name='follow_user'),
    path('unfollow/<username>/', views.unfollow_user, name='unfollow_user')
]

Social_Web/post/urls.py
from django.urls import path 
from post import views


app_name = 'post'

urlpatterns = [
    path('upload/', views.upload, name='upload' ),
    path('like/<pk>/', views.like , name = 'like'),
    path('unlike/<pk>/', views.unlike , name = 'unlike'),
    path('detail-post/<pk>', views.detail_post, name='detail_post'),
    path('delete-post/<pk>', views.delete_post, name='delete_post')
]

Social_Web/account/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin


class SocialUserManager(BaseUserManager):
    def create_user(self, email, roll,username, password=None):
        
        if not email:
            raise ValueError("Users must have an email address")
        if not username:
            raise ValueError("Users must have an Username")
        if not roll:
            raise ValueError("Users must have an Roll")
        
        user = self.model(
            email=self.normalize_email(email),
            roll=roll,
            username = username
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, roll,username, password=None):
        
        user = self.create_user(
            email,
            password=password,
            roll=roll,
            username = username
        )
        user.is_superuser = True
        user.save(using=self._db)
        return user


class SocialUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        max_length=255,
        unique=True,
    )
    roll = models.CharField(max_length=15, unique=True)
    username = models.CharField(max_length=50, unique=True)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    objects = SocialUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["roll", "username"]

    def __str__(self):
        return self.email
    
    def get_group_permissions(obj=None):
        return obj

   
def upload_profile_pic(instance, filename):
    return 'profile_pics\{username}\{filename}'.format(username=instance.user.username,filename=filename)

class UserProfile(models.Model):
    user = models.OneToOneField(SocialUser, on_delete=models.CASCADE, related_name='profile')
    profile_pic = models.ImageField(upload_to=upload_profile_pic, default='default.jpg')
    bio = models.CharField(max_length=100, blank=True, null=True)
    full_name = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return str(self.user.username)
    

class Follow(models.Model):
    follower = models.ForeignKey(SocialUser, on_delete=models.CASCADE, related_name='follower')
    following = models.ForeignKey(SocialUser, on_delete=models.CASCADE, related_name='following')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.follower.username) + ' follows ' + str(self.following.username)

Social_Web/account/forms.py
from django import forms
from .models import SocialUser,UserProfile
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class NewUserForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        label="",
        widget=(forms.TextInput(attrs={'placeholder':'Email Address'}))
    )
    roll = forms.CharField(
        required=True,
        label="",
        widget=(forms.TextInput(attrs={'placeholder':'Roll'}))
    )
    username = forms.CharField(
        required=True,
        label="",
        widget=(forms.TextInput(attrs={'placeholder':'Username'}))
    )
    password1 = forms.CharField(
        required=True,
        label="",
        widget=(forms.PasswordInput(attrs={'placeholder': 'Password'}))
    )
    password2 = forms.CharField(
        required=True,
        label="",
        widget=(forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))
    )


    class Meta:
        model = SocialUser
        fields = ('email','roll','username','password1','password2')

class LoginForm(forms.Form):
    username = forms.CharField(
        required=True,
        label="",
        widget=(forms.TextInput(attrs={'placeholder':'Enter your Roll or Username'}))
    )
    password = forms.CharField(
        required=True,
        label="",
        widget=(forms.PasswordInput(attrs={'placeholder': 'Enter your Password'}))
    )
    

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields =('profile_pic', 'bio', 'full_name')

Social_Web/account/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.db.models import Q

from .forms import NewUserForm, LoginForm, EditProfileForm
from .models import UserProfile, SocialUser, Follow
from post.models import Post,Like
from post.forms import PostForm

# Create your views here.

def authenticate(username=None, password=None):
    
    user =SocialUser.objects.filter(username=username).first()
    if user is None:
        user = SocialUser.objects.filter(roll=username).first()
    if user is not None:
        if check_password(password,user.password):
            return user
    return None
    

def signup(request):
    form = NewUserForm()
    if request.method == 'POST':
        form = NewUserForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            user_profile = UserProfile.objects.create(user=user)
            return HttpResponseRedirect(reverse('account:login'))
    return render(request, 'signup.html', context={'form':form})


def login_view(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('home'))
            return render(request, 'login.html', context={'form':form, 'error':"Enter correct information"})
    return render(request, 'login.html', context={'form':form})


@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('account:login'))


@login_required
def home(request):
    followed = Follow.objects.filter(follower=request.user)
    posts = Post.objects.filter(Q(user__in = followed.values_list('following')) | Q(user = request.user)).order_by('-post_created')
    likes = Like.objects.filter(liker=request.user)
    liked = likes.values_list('post', flat=True)
    return render(request, 'home.html', context={'posts':posts, 'likes':liked})

@login_required
def user_profile(request):
    try:
        user_profile = UserProfile.objects.get(user=request.user)
        user_posts = Post.objects.filter(user=request.user).order_by('-post_created')
        
        
    except:
        user_profile = None
    
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            form = PostForm()
    return render(request, 'profile.html', context={'user_profile':user_profile, 'user_posts':user_posts, 'form':form})

@login_required
def search_user(request):
    if request.method == 'GET':
        data = request.GET.get('search')
        results = SocialUser.objects.filter(username__icontains = data)

    return render(request, 'home.html', context={'results':results})

@login_required
def other_profile(request,username):
    other_user = SocialUser.objects.get(username=username)
    user_posts = Post.objects.filter(user=other_user).order_by('-post_created')
    followed = Follow.objects.filter(follower=request.user, following=other_user)

    if other_user == request.user:
        return HttpResponseRedirect(reverse('account:profile'))

    return render(request, 'other_profile.html', context={'other_user': other_user, 'user_posts':user_posts, 'followed':followed} )


@login_required
def follow_user(request, username):
    other_user = SocialUser.objects.get(username=username)
    followed = Follow.objects.filter(follower=request.user, following=other_user)
    if not followed :
        follow = Follow(follower=request.user, following=other_user)
        follow.save()


    return HttpResponseRedirect(reverse('account:other_profile', kwargs={'username': username}))

@login_required
def unfollow_user(request, username):
    other_user = SocialUser.objects.get(username=username)
    followed = Follow.objects.filter(follower=request.user, following=other_user)
    if followed:
        followed.delete()
    return HttpResponseRedirect(reverse('account:other_profile', kwargs={'username': username}))


@login_required
def edit_profile(request):
    try:
        user_profile = request.user.profile
    except UserProfile.DoesNotExist:
        user_profile = UserProfile(user = request.user)

    form = EditProfileForm(instance=user_profile)
    if request.method == 'POST':
        form = EditProfileForm(request.POST, request.FILES,instance=user_profile)
        if form.is_valid():
            form.save(commit=True)
            
            
            return HttpResponseRedirect(reverse('account:profile'))
    return render(request, 'edit_profile.html', context={'form':form})

Social_Web/account/templates/edit_profile.html
{% extends 'navbar.html' %}
{% load static %}
{% load crispy_forms_tags %} 
{% block body %}
<div class="container-md mt-5">
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-5">
            <div class="shadow-lg p-5 mb-5 bg-light rounded">
                <form action="" method="POST" enctype="multipart/form-data">
            
                    {{form|crispy}}
                    {% csrf_token %}
    
                    <button type="submit" class="btn btn-primary">Update Profile</button>
                    <a href="{% url 'account:profile' %}"><button type="button" class="btn btn-secondary">Cancel</button></a>
    
                </form>
            </div>
            
        </div>
    </div>

</div>


{% endblock %}

Social_Web/account/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 

{% block css %}
<style>
    .login{
        width: 500px;
        margin: auto;
        margin-top: 50px;
        padding: 30px 20px;
        border: 2px solid #eee;
    }
    .login-head{
        margin-bottom: 30px;
    }
</style>

{% endblock %}

{% block body %}

<div class="container">
    <div class="login shadow-sm rounded">
        <h3 class="login-head">Login here</h3>
        {% if error %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{error}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endif %}
        <form method="POST">
            {{form|crispy}}
            {% csrf_token %}

            <button type="submit" style="width: 100%;margin: 20px 0;" class="btn btn-primary">Login</button>
        </form>
        <p>Haven't you any account ? <a href="{% url 'account:signup' %}">Signup</a></p>
    </div>
</div>
    

{% endblock %}

Social_Web/account/templates/other_profile.html
{% extends 'navbar.html' %}
{% load static %}
{% load crispy_forms_tags %} 
{% block body %}

    <div class="container-md mt-md-5 mt-4">
        <div class="row">
            <div class="col-lg-2">

            </div>
            <div class="col-lg-10 pt-5 pt-md-1 col-12">
                <div class="container-md pt-2">
                    <div class=" row">
                        <div class="col-4 col-sm-3  col-md-4 text-center">
                            <img src="/media/{{other_user.profile.profile_pic}}" width="200" height="200" alt="" srcset="" class="d-md-block d-none rounded-circle">
                            <img src="/media/{{other_user.profile.profile_pic}}" width="100" height="100" alt="" srcset="" class="d-md-none rounded-circle">
                        </div>
                        <div class="col-8 col-sm-9 col-md-8  ">
                            <div class="">
                                <span class="" style="font-size: 20px; font-weight: 600;">{{other_user.username}}</span>
                                {% if followed %}
                                <a href="{% url 'account:unfollow_user' username=other_user.username %}" class="text-dark d-md-inline d-none bg-light p-2 ml-5 rounded text-bold text-decoration-none">Unfollow</a>
                                {% else %}
                                <a href="{% url 'account:follow_user' username=other_user.username %}" class="text-dark d-md-inline d-none bg-light p-2 ml-5 rounded text-bold text-decoration-none">Follow</a>
                                {% endif %}
                            </div>
                            <div class="d-md-none mt-4">
                                {% if followed %}
                                <a href="{% url 'account:unfollow_user' username=other_user.username %}" class="text-dark bg-light p-2  rounded text-bold text-decoration-none">Unfollow</a>
                                {% else %}
                                <a href="{% url 'account:follow_user' username=other_user.username %}" class="text-dark bg-light p-2  rounded text-bold text-decoration-none">Follow</a>
                                {% endif %}
                            </div>
                            <div class="d-none d-md-block  flex mt-4 ">
                                <span class=" mr-md-4">{{other_user.post.count}} posts</span>
                                <span class="mr-md-4">{{other_user.following.count}} followers</span>
                                <span >{{other_user.follower.count}} following</span>
        
                            </div>
                            <div class= "d-md-block d-none mt-4">
                                <h5>{{other_user.profile.full_name}}</h5>
                                <p>{{ other_user.profile.bio}}</p>
                            </div>
                        </div>
                       
                    </div>
                    <div class=" d-md-none flex">
                        <span class="mr-1 ">{{other_user.post.count}} posts</span>
                        <span class="mr-1 ">{{other_user.following.count}} followers</span>
                        <span >{{other_user.follower.count}} following</span>

                    </div>
                    <div class="d-md-none">
                        <h5>{{other_user.profile.full_name}}</h5>
                        <p>{{ other_user.profile.bio}}</p>
                    </div>
                    <hr>
                </div>
            </div>
            <div class="col-lg-1">

            </div>

        </div>
        
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                {% for post in user_posts %}
                    <div class="bg-image d-inline-block hover-overlay"  style="width: 32%; height: 260px;" >
                       <a href="{% url 'post:detail_post' pk=post.pk %}">

                        {% if post.media_type_html == "video" %}
                            <video style="width: 32%; height: 260px;" class="w-100 h-100" alt="This is video" > <source src="/media/{{ post.content }}" > </video>
                        {% elif post.media_type_html == "image" %}
                            <img src="/media/{{post.content}}" class="w-100" style="width: 32%; height: 260px;" alt="">
                        {% endif %}
                       </a>
                        <div
                            class="mask"
                            style="
                            background: linear-gradient(
                                45deg,
                                hsla(168, 85%, 52%, 0.5),
                                hsla(263, 88%, 45%, 0.5) 100%
                            );
                            "
                        ></div>
                    </div>

                {% endfor %}
            </div>
            
            <div class="col-md-2"></div>
        </div>
        
    </div>


{% endblock %}

Social_Web/account/templates/profile.html
{% extends 'navbar.html' %}
{% load static %}
{% load crispy_forms_tags %} 
{% block body %}

    <div class="container-md mt-md-5 mt-4">
        <div class="row">
            <div class="col-lg-2">

            </div>

            <div class="col-lg-10 pt-5 pt-md-1 col-12">
                <div class="container-md pt-2">
                    <div class=" row">
                        <div class="col-4 col-sm-3  col-md-4 text-center">
                            <img src="/media/{{user.profile.profile_pic}}" width="200" height="200" alt="" srcset="" class="d-md-block d-none rounded-circle">
                            <img src="/media/{{user.profile.profile_pic}}" width="100" height="100" alt="" srcset="" class="d-md-none rounded-circle">
                        </div>
                        <div class="col-8 col-sm-9 col-md-8  ">
                            <div class="">
                                <span class="" style="font-size: 20px; font-weight: 600;">{{user.username}}</span>
                                <a href="{% url 'account:edit_profile' %}" class="text-dark d-md-inline d-none bg-light p-2 ml-5 rounded text-bold text-decoration-none">Edit Profile</a>
                            </div>
                            <div class="d-md-none mt-4">
                                <a href="{% url 'account:edit_profile' %}" class="text-dark bg-light p-2  rounded text-bold text-decoration-none">Edit Profile</a>

                            </div>
                            <div class="d-none d-md-block  flex mt-4 ">
                                <span class=" mr-md-4">{{user.post.count}} posts</span>
                                <span class="mr-md-4">{{user.following.count}} followers</span>
                                <span >{{user.follower.count}} following</span>
        
                            </div>
                            <div class= "d-md-block d-none mt-4">
                                <h5>{{user.profile.full_name}}</h5>
                                <p>{{ user.profile.bio}}</p>
                            </div>
                        </div>
                       
                    </div>
                    <div class=" d-md-none flex">
                        <span class="mr-1 ">{{user.post.count}} posts</span>
                        <span class="mr-1 ">{{user.following.count}} followers</span>
                        <span >{{user.follower.count}} following</span>

                    </div>
                    <div class="d-md-none">
                        <h5>{{user.profile.full_name}}</h5>
                        <p>{{ user.profile.bio}}</p>
                    </div>

                    <div class=" d-inline-block cursor-pointer m-5" style="cursor: pointer;" >
                        <a href="{% url 'post:upload' %}" class="text-dark ">
                            <i class="fa-solid fa-plus bg-light border rounded-circle " style="font-size: 50px ; font-weight: 100; padding: 20px 25px;"></i>
                            <br><span style="margin-left: 32px;">New</span>               
                        </a>        
                    </div>
                    <hr>
                </div>


            </div>
            <div class="col-lg-1">

            </div>

        </div>
        
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                {% for post in user_posts %}
                    <div class="bg-image d-inline-block hover-overlay"  style="width: 32%; height: 260px;" >
                       <a href="{% url 'post:detail_post' pk=post.pk %}">
                        {% if post.media_type_html == "video" %}
                            <video style="width: 32%; height: 260px;" class="w-100 h-100" alt="This is video" > <source src="/media/{{ post.content }}" > </video>
                        {% elif post.media_type_html == "image" %}
                            <img src="/media/{{post.content}}" class="w-100" style="width: 32%; height: 260px;" alt="">
                        {% endif %}
                    </a>
                        <div
                            class="mask"
                            style="
                            background: linear-gradient(
                                45deg,
                                hsla(168, 85%, 52%, 0.5),
                                hsla(263, 88%, 45%, 0.5) 100%
                            );
                            "
                        ></div>
                    </div>

                {% endfor %}
            </div>
            
            <div class="col-md-2"></div>
        </div>
        
    </div>


{% endblock %}

Social_Web/account/templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block css %}
<style>
    .signup{
        width: 500px;
        margin: auto;
        margin-top: 50px;
        padding: 30px 20px;
        border: 2px solid #eee;
    }
    .signup-head{
        margin-bottom: 30px;
    }
</style>

{% endblock %}

{% block body %}
<div class="container">
    <div class="signup shadow-lg rounded">
        <h3 class="signup-head">SignUp here</h3>
        <form action="" method="POST">
            {{form|crispy}}
            {% csrf_token %}

            <button type="submit" style="width: 100% ;margin: 20px 0;" class="btn btn-primary" >SignUp</button>
        </form>
        <p>Did you have any account ? <a href="{% url 'account:login'  %}">Login</a></p>
    </div>
</div>

{% endblock %}