Social_Web/Social_Web/urls.py
from django.contrib import admin
from django.urls import path, include
from account import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('posts/', include('post.urls')),
    path('', views.home, name='home')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Social_Web/account/urls.py
from django.urls import path
from account import views

app_name = "account"

urlpatterns = [
    path('signup/', views.signup , name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('search-user/', views.search_user, name='search_user'),
    path('user/<username>/', views.other_profile, name='other_profile'),
    path('follow/<username>/', views.follow_user, name='follow_user'),
    path('unfollow/<username>/', views.unfollow_user, name='unfollow_user')
]

Social_Web/post/urls.py
from django.urls import path 
from post import views


app_name = 'post'

urlpatterns = [
    path('upload/', views.upload, name='upload' ),
    path('like/<pk>/', views.like , name = 'like'),
    path('unlike/<pk>/', views.unlike , name = 'unlike'),
    path('detail-post/<pk>', views.detail_post, name='detail_post'),
    path('delete-post/<pk>', views.delete_post, name='delete_post')
]

Social_Web/post/models.py
from django.db import models
from account.models import SocialUser, UserProfile
from mimetypes import guess_type
# Create your models here.

  
def upload_post(instance, filename):
    return 'posts\{username}\{filename}'.format(username=instance.user.username,filename=filename)


class Post(models.Model):
    user = models.ForeignKey(SocialUser, on_delete=models.CASCADE, related_name='post')
    content = models.FileField(upload_to= upload_post)
    caption = models.CharField(max_length=255, blank=True, null=True)
    post_created = models.DateTimeField(auto_now_add=True)
    post_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username + "'s post ->" + str(self.pk)
    
    def media_type_html(self):
        type_tuple = guess_type(self.content.url, strict=True)
        if (type_tuple[0]).__contains__("image"):
            return "image"
        elif (type_tuple[0]).__contains__("video"):
            return "video"


class Like(models.Model):
    liker = models.ForeignKey(SocialUser, on_delete=models.CASCADE, related_name='liker')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='liked_post')

    def __str__(self):
        return self.liker.username + ' likes '  + self.post.user.username +"'s " + str(self.post.pk)

Social_Web/post/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    content = forms.FileField(widget=forms.FileInput(attrs={'accept':'image/*,video/*'}))
    class Meta:
        model = Post
        fields = ('content', 'caption')

Social_Web/post/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .forms import PostForm
from .models import Like, Post

# Create your views here.


@login_required
def upload(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            
            return HttpResponseRedirect(reverse('home'))
    return render(request, 'upload.html', context={'form':form})


@login_required
def like(request, pk):
    post = Post.objects.get(pk=pk)
    like = Like.objects.create(liker=request.user, post=post)

    return HttpResponseRedirect(reverse('home'))

@login_required
def unlike(request, pk):
    post = Post.objects.get(pk=pk)
    unlike = Like.objects.filter(liker=request.user, post=post)
    print(unlike)

    unlike.delete()

    return HttpResponseRedirect(reverse('home'))

@login_required
def detail_post(request, pk):
    post = Post.objects.get(pk=pk)
    deletable = False
    if post.user == request.user:
        deletable = True

    return render(request, 'detail_post.html', context={'post':post, 'canDelete': deletable})

@login_required
def delete_post(request, pk):
    post = Post.objects.get(pk=pk)
    deleted = post.delete()
    return HttpResponseRedirect(reverse('account:profile'))

Social_Web/post/templates/detail_post.html
{% extends 'navbar.html' %}
{% load static %}
{% load crispy_forms_tags %} 
{% block body %}
<div class="container-md mt-5">
    <div class="row">
        <div class="col-sm-2 col-md-3 col-xl-2">

        </div>
        <div class="col-12 col-sm-8 col-md-6 col-xl-4 mt-5">
            
            
                <div class="">

                    <div class="d-flex justify-content-between my-2">
                        <div>
                            <a href="{% url 'account:other_profile' username=post.user.username %}" class="text-decoration-none text-dark ">
                                <img src="/media/{{post.user.profile.profile_pic}}" alt="" height="40px" width="40px" class="rounded-circle" style="border: 2px solid rgb(243, 72, 72); padding: 2px;"> 
                                <span class=" mx-2 font-weight-bold"> {{post.user.username}} </span> 
                                <span> {{ post.post_created|timesince}} ago </span> 
                            </a>
                        </div>
                        <div>
                            {% if canDelete %}
                                <a href="{% url 'post:delete_post' pk=post.pk %}">
                                    <button class="btn btn-danger">Delete</button>
                                </a>
                            {% endif %}
                        </div>
                    
                    </div>
                     
                    
                    {% if post.media_type_html == "video" %}
                        <video style="height: 450px;" class="w-100" alt="This is video" controls> <source src="/media/{{ post.content }}" > </video>
                    {% elif post.media_type_html == "image" %}
                    <img src="/media/{{ post.content }}" alt="" class="w-100 " height="450px">
                    {% endif %}
                    <div class="p-2">
                        <span>{{  post.liked_post.count}} likes</span> <br>
                        {% if post.caption %}
                            <span class=" font-weight-bold" >{{ post.user.username }}</span>
                            <span>{{ post.caption }}</span>
                        {% endif %}


                    </div>
                </div>
                <br>
        </div>
        <div class="col-sm-2 col-md-3 col-xl-6">
            
        </div>
    </div>

</div>




{% endblock %}

Social_Web/post/templates/home.html
{% extends 'navbar.html' %} 

{% block body %}
    <div class="container-md ">
        {% if results %}
        <div class="row mt-2">
            <div class=" col-sm-3">
            </div>
            <div class="col-12 col-sm-9">
                <h3 class="mt-5 mb-2">People you may know</h3>
            </div>
        </div>
        
        <div class="mt-1">
            {% for result in results %}
                <div class="row mt-sm-4 mt-3">
                    <div class="col-1 col-sm-3"></div>
                    <div class="col-10 col-sm-9">
                        <div class="d-flex">
                            <div >
                                <img src="/media/{{ result.profile.profile_pic}}" height="40px" width="40px" class="rounded-circle" alt="">
                            </div>
                            <div class="d-flex flex-column mx-sm-4 mx-3">
                                <a href="{% url 'account:other_profile' username=result.username %}" class="text-dark">
                                    <span style="font-size: 18px; font-weight: 500;"> {{result.username}}</span>
                                </a>
                                <span class="text-secondary " style="font-size: 14px; font-weight: 400;"> {{ result.profile.full_name }}</span>                     
                            </div>
                        </div>

                    
                    </div>
                </div>
            {% endfor %}
        </div>
        {% else %}

        <div class="row">
            <div class="col-sm-2 col-md-3 col-xl-2">

            </div>
            <div class="col-12 col-sm-8 col-md-6 col-xl-4 mt-5">
                <div>
                    <h4></h4>
                </div>
                {% for post in posts %}
                    <div class="">
                        <p> <a href="{% url 'account:other_profile' username=post.user.username %}" class="text-decoration-none text-dark ">
                                <img src="/media/{{post.user.profile.profile_pic}}" alt="" height="40px" width="40px" class="rounded-circle" style="border: 2px solid rgb(243, 72, 72); padding: 2px;"> 
                                <span class=" mx-2 font-weight-bold"> {{post.user.username}} </span> 
                                <span> {{ post.post_created|timesince}} ago </span> 
                            </a>
                        </p>
                        {% if post.media_type_html == "video" %}
                            <video style="height: 450px;" class="w-100" alt="This is video" controls> <source src="/media/{{ post.content }}" > </video>
                        {% elif post.media_type_html == "image" %}
                        <img src="/media/{{ post.content }}" alt="" class="w-100 " height="450px">
                        {% endif %}
                        <div class="p-2">
                            {% if post.pk in likes %}
                            <a href="{% url 'post:unlike' pk=post.pk %}"><i class="fas fa-heart" style="font-size:36px; color: red;"></i></a>
                            {% else %}
                            <a href="{% url 'post:like' pk=post.pk %}"><i class="fa-regular fa-heart" style="font-size:36px; color: red;"></i></a>
                            
                            {% endif %}
                            <br>
                            <span>{{  post.liked_post.count}} likes</span> <br>
                            {% if post.caption %}
                                <span class=" font-weight-bold" >{{ post.user.username }}</span>
                                <span>{{ post.caption }}</span>
                            {% endif %}


                        </div>
                    </div>
                    <br>
                {% endfor %}
            </div>
            <div class="col-sm-2 col-md-3 col-xl-6">
                
            </div>
        </div>

        {% endif %}
    </div>

    
    <scripts>
        
    </scripts>

{% endblock %}

Social_Web/post/templates/upload.html
{% extends 'navbar.html' %}
{% load static %}
{% load crispy_forms_tags %} 

{% block body %}
    <div class="container-md mt-5">
        <div class="row">
            <div class="col-md-3">

            </div>
            <div class="col-md-5">
                <div class="shadow-lg p-5 mb-5 bg-light rounded">
                    <form action="" method="POST" enctype="multipart/form-data">
                
                        {{form|crispy}}
                        {% csrf_token %}
        
                        <button type="submit" class="btn btn-primary">Post</button>
                        <a href="{% url 'home' %}"><button type="button" class="btn btn-secondary">Cancel</button></a>
        
                    </form>
                </div>
                
            </div>
        </div>
        

    </div>

{% endblock %}